version: '3.8'

services:
  frontend:
    build: ./AS-03-Frontend
    container_name: as03-frontend
    ports:
      - "3000:80" 
    restart: unless-stopped

  backend:
    build: ./AS-03-Backend
    container_name: as03-backend
    environment:
      - DB_HOST=${RDS_ENDPOINT}
      - DB_PORT=5432
      - DB_USER=${RDS_USER}
      - DB_PASSWORD=${RDS_PASSWORD}
      - DB_NAME=keycloak_db # You can change this later if FastAPI uses a different DB
    ports:
      - "8000:8000"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: as03-keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://${RDS_ENDPOINT}:5432/keycloak_db
      - KC_DB_USERNAME=${RDS_USER}
      - KC_DB_PASSWORD=${RDS_PASSWORD}
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_PROXY=edge
    command: start-dev 
    ports:
      - "8080:8080"
    restart: unless-stopped