name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Build the Backend
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AS-03-Backend # Tells CI to look here
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build Backend Image
        run: docker build -t backend:latest .

  # Job 2: Build the Frontend
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AS-03-Frontend # Tells CI to look here
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Build Frontend Image
        run: docker build -t frontend:latest .